import type { Period } from "@/types";

export const PERIODS: Period[] = [
  {
    id: "islamiyet-oncesi-turk-tarihi",
    slug: "islamiyet-oncesi-turk-tarihi",
    name: "İslamiyet Öncesi Türk Tarihi",
    startYear: -700,
    endYear: 1040,
    color: "#E8A045",
    description: "İskitlerden Oğuzlara İslamiyet öncesi Türk devletleri dönemi",
  },
  {
    id: "ilk-turk-islam-devletleri",
    slug: "ilk-turk-islam-devletleri",
    name: "İlk Türk İslam Devletleri",
    startYear: 840,
    endYear: 1520,
    color: "#7C3AED",
    description: "Karahanlılardan Memlüklere ilk Türk-İslam devletleri dönemi",
  },
  {
    id: "buyuk-selcuklu",
    slug: "buyuk-selcuklu",
    name: "Büyük Selçuklu",
    startYear: 1040,
    endYear: 1157,
    color: "#2E8B57",
    description: "Büyük Selçuklu İmparatorluğu dönemi",
  },
  {
    id: "anadolu-selcuklu",
    slug: "anadolu-selcuklu",
    name: "Anadolu Selçuklu",
    startYear: 1077,
    endYear: 1308,
    color: "#3CB371",
    description: "Anadolu Selçuklu Devleti dönemi",
  },
  {
    id: "osmanli-kurulus-yukselme",
    slug: "osmanli-kurulus-yukselme",
    name: "Osmanlı Kuruluş ve Yükselme",
    startYear: 1299,
    endYear: 1579,
    color: "#C8102E",
    description: "Osman Bey'den Sokullu'ya Osmanlı Devleti'nin kuruluş ve yükselme dönemi",
  },
  {
    id: "osmanlı-duraklama",
    slug: "osmanli-duraklama",
    name: "Osmanlı Duraklama",
    startYear: 1579,
    endYear: 1699,
    color: "#CD5C5C",
    description: "Osmanlı İmparatorluğu'nun duraklama dönemi",
  },
  {
    id: "osmanlı-gerileme",
    slug: "osmanli-gerileme",
    name: "Osmanlı Gerileme",
    startYear: 1699,
    endYear: 1792,
    color: "#FA8072",
    description: "Osmanlı İmparatorluğu'nun gerileme dönemi",
  },
  {
    id: "osmanlı-dağılma",
    slug: "osmanli-dagilma",
    name: "Osmanlı Dağılma",
    startYear: 1792,
    endYear: 1922,
    color: "#FFA07A",
    description: "Osmanlı İmparatorluğu'nun dağılma dönemi",
  },
  {
    id: "kurtulus-savasi",
    slug: "kurtulus-savasi",
    name: "Kurtuluş Savaşı",
    startYear: 1919,
    endYear: 1923,
    color: "#FF6347",
    description: "Türk Kurtuluş Savaşı dönemi",
  },
  {
    id: "turk-cumhuriyeti",
    slug: "turk-cumhuriyeti",
    name: "Türkiye Cumhuriyeti",
    startYear: 1923,
    endYear: null,
    color: "#E30A17",
    description: "Türkiye Cumhuriyeti dönemi",
  },
];
