import type { Period } from "@/types";

export const PERIODS: Period[] = [
  {
    id: "ilk-turk-devletleri",
    slug: "ilk-turk-devletleri",
    name: "İlk Türk Devletleri",
    startYear: 220,
    endYear: 1040,
    color: "#8B4513",
    description: "Hunlar'dan Karahanlılar'a ilk Türk devletleri dönemi",
  },
  {
    id: "buyuk-selcuklu",
    slug: "buyuk-selcuklu",
    name: "Büyük Selçuklu",
    startYear: 1040,
    endYear: 1157,
    color: "#2E8B57",
    description: "Büyük Selçuklu İmparatorluğu dönemi",
  },
  {
    id: "anadolu-selcuklu",
    slug: "anadolu-selcuklu",
    name: "Anadolu Selçuklu",
    startYear: 1077,
    endYear: 1308,
    color: "#3CB371",
    description: "Anadolu Selçuklu Devleti dönemi",
  },
  {
    id: "osmanlı-kuruluş",
    slug: "osmanli-kurulus",
    name: "Osmanlı Kuruluş",
    startYear: 1299,
    endYear: 1453,
    color: "#DC143C",
    description: "Osmanlı Devleti'nin kuruluş ve yükseliş başlangıcı",
  },
  {
    id: "osmanlı-yükseliş",
    slug: "osmanli-yukselis",
    name: "Osmanlı Yükseliş",
    startYear: 1453,
    endYear: 1579,
    color: "#B22222",
    description: "Osmanlı İmparatorluğu'nun yükseliş dönemi",
  },
  {
    id: "osmanlı-duraklama",
    slug: "osmanli-duraklama",
    name: "Osmanlı Duraklama",
    startYear: 1579,
    endYear: 1699,
    color: "#CD5C5C",
    description: "Osmanlı İmparatorluğu'nun duraklama dönemi",
  },
  {
    id: "osmanlı-gerileme",
    slug: "osmanli-gerileme",
    name: "Osmanlı Gerileme",
    startYear: 1699,
    endYear: 1792,
    color: "#FA8072",
    description: "Osmanlı İmparatorluğu'nun gerileme dönemi",
  },
  {
    id: "osmanlı-dağılma",
    slug: "osmanli-dagilma",
    name: "Osmanlı Dağılma",
    startYear: 1792,
    endYear: 1922,
    color: "#FFA07A",
    description: "Osmanlı İmparatorluğu'nun dağılma dönemi",
  },
  {
    id: "kurtulus-savasi",
    slug: "kurtulus-savasi",
    name: "Kurtuluş Savaşı",
    startYear: 1919,
    endYear: 1923,
    color: "#FF6347",
    description: "Türk Kurtuluş Savaşı dönemi",
  },
  {
    id: "turk-cumhuriyeti",
    slug: "turk-cumhuriyeti",
    name: "Türkiye Cumhuriyeti",
    startYear: 1923,
    endYear: null,
    color: "#E30A17",
    description: "Türkiye Cumhuriyeti dönemi",
  },
];
